#!/usr/bin/env sh
set -eu

APP_HOME=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

set -a
# shellcheck disable=SC1091
. "$APP_HOME/prod.env"
set +a

exec java -cp "$APP_HOME/app.jar:$APP_HOME/lib/*" sgrv.be.Main "$@"
